### ISSUE TITLE
[Feature Request] : Need to support LoRA and QLoRA

### ISSUE THREAD

**Issue by yongzhemiaolegemi** [PKU-Alignment/align-anything#17]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/align-anything/issues) and [Discussions](https://github.com/PKU-Alignment/align-anything/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/align-anything/discussions/new).

**Comment by yongzhemiaolegemi** [comment]
#16

**Comment by yongzhemiaolegemi** [comment]
#16 LoRA and QLoRA supported in this pr

**Comment by Gaiejj** [comment]
Feel free to ask @yongzhemiaolegemi if you encounter any issues!
