### ISSUE TITLE
[Question] SFT data format for Emu3

### ISSUE THREAD

**Issue by yimuu** [PKU-Alignment/align-anything#86]
### Required prerequisites

- [X] I have read the documentation <https://align-anything.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/align-anything/issues) and [Discussions](https://github.com/PKU-Alignment/align-anything/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/align-anything/discussions/new).

### Questions

The data format of ti2t t2i when SFT Emu3

**Comment by htlou** [comment]
We’ve included examples of both understanding and generation training data for fine-tuning Emu3 in our documentation: https://align-anything.readthedocs.io/en/latest/training/any_to_any.html. You can use these examples for debugging purposes or create your own dataset following the same format.
